title: Ezequiel Santos
position: ğŸ‘¨ğŸ»â€ğŸ’» Software Developer and Creative Technologist
affiliation: Your Affiliation
email: ezefranca (at) 
keywords: ezefranca iOS Developer Game Developer
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/
github: github
lattes: lattes
twitter: twitter
avatar: ./assets/img/profile-img.webp
favicon: ./assets/img/favicon.webp
favicon_dark: ./assets/img/favicon.webp
description: Ezequiel Santos personal homepage.
canonical: https://ezequiel.app/
remote_theme: yaoyao-liu/minimal-light
